### ISSUE TITLE
Tudnád dokumentálni hogy mit hogy csináltál?

### ISSUE THREAD

**Issue by krinistof** [palmarci/ekreta-private-api#1]
Szeretném használni a szkriptedet, mint forrás saját programhoz, viszont nem beszélek Javascriptül :/
Tudnál valamilyen szinten segítséget nyújtani, legalább olyan szinten, hogy rámutatsz, hogyan lehetne -1-ről 0-ra lépni

Válaszodat előre köszönöm! :smile:

**Comment by palmarci** [comment]
a közeljövőben valószíinűleg pythonban újraírom, addig nyugodtan kérdezhetsz, nézd meg a biomat

**Comment by palmarci** [comment]
nézd meg a leírást
