### ISSUE TITLE
Kérdések

### ISSUE THREAD

**Issue by baltitenger** [palmarci/ekreta-private-api#2]
Én is szeretném használni a kréta APIját, mivel az sokkal gyorsabb lehet a weboldalnál, és így legalább nem a HTMLből kell kibogarászni az adatokat. Annyit szeretnék megtudni, hogy mi az a client_id, nem látom, hogy a kódban ez bárhol be lenne állítva. És honnan tudtál meg ilyeneket? Én csak egy emulátorban néztem meg wiresharkkal, de az app látszólag a kretaglobalmobileapi.ekreta.hut használja, ami egy microsoft azureos cucc. Nagyon megköszönném, ha minél több információt meg tudnál osztani.

**Comment by boapps** [comment]
https://github.com/boapps/e-kreta-api-docs

**Comment by palmarci** [comment]
Hat koszonom szepen a valaszt, sajnos lusta voltam megcsinálni rendesen meg nem is volt komoyabban celom, de nagyon orulok hogy nem csak en szorakozok ilyenekkel szabadidomben.
